"""initial_schema

Revision ID: 96f8fee1d58e
Revises: 
Create Date: 2026-03-29 16:54:06.278679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96f8fee1d58e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biometric_uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('total_teachers', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planilla_outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('total_teachers', sa.Integer(), nullable=False),
    sa.Column('total_hours', sa.Integer(), nullable=False),
    sa.Column('total_payment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'year', name='uq_planilla_month_year')
    )
    op.create_table('teachers',
    sa.Column('ci', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('external_permanent', sa.String(length=50), nullable=True),
    sa.Column('academic_level', sa.String(length=100), nullable=True),
    sa.Column('profession', sa.String(length=200), nullable=True),
    sa.Column('specialty', sa.String(length=200), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('sap_code', sa.String(length=50), nullable=True),
    sa.Column('invoice_retention', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ci')
    )
    op.create_index(op.f('ix_teachers_ci'), 'teachers', ['ci'], unique=False)
    op.create_table('biometric_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('teacher_ci', sa.String(length=20), nullable=False),
    sa.Column('teacher_name', sa.String(length=200), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('entry_time', sa.Time(), nullable=True),
    sa.Column('exit_time', sa.Time(), nullable=True),
    sa.Column('worked_minutes', sa.Integer(), nullable=True),
    sa.Column('shift', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['biometric_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id', 'teacher_ci', 'date', 'entry_time', name='uq_biometric_record')
    )
    op.create_index(op.f('ix_biometric_records_teacher_ci'), 'biometric_records', ['teacher_ci'], unique=False)
    op.create_index(op.f('ix_biometric_records_upload_id'), 'biometric_records', ['upload_id'], unique=False)
    op.create_table('designations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_ci', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('semester', sa.String(length=50), nullable=False),
    sa.Column('group_code', sa.String(length=20), nullable=False),
    sa.Column('schedule_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('semester_hours', sa.Integer(), nullable=True),
    sa.Column('monthly_hours', sa.Integer(), nullable=True),
    sa.Column('weekly_hours', sa.Integer(), nullable=True),
    sa.Column('weekly_hours_calculated', sa.Integer(), nullable=True),
    sa.Column('schedule_raw', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_ci'], ['teachers.ci'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_designations_teacher_ci'), 'designations', ['teacher_ci'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_ci', sa.String(length=20), nullable=False),
    sa.Column('designation_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('scheduled_start', sa.Time(), nullable=False),
    sa.Column('scheduled_end', sa.Time(), nullable=False),
    sa.Column('actual_entry', sa.Time(), nullable=True),
    sa.Column('actual_exit', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('academic_hours', sa.Integer(), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('biometric_record_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['biometric_record_id'], ['biometric_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_ci'], ['teachers.ci'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_ci', 'designation_id', 'date', 'scheduled_start', name='uq_attendance_record')
    )
    op.create_index(op.f('ix_attendance_records_date'), 'attendance_records', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_records_designation_id'), 'attendance_records', ['designation_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_teacher_ci'), 'attendance_records', ['teacher_ci'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_records_teacher_ci'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_designation_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_date'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_designations_teacher_ci'), table_name='designations')
    op.drop_table('designations')
    op.drop_index(op.f('ix_biometric_records_upload_id'), table_name='biometric_records')
    op.drop_index(op.f('ix_biometric_records_teacher_ci'), table_name='biometric_records')
    op.drop_table('biometric_records')
    op.drop_index(op.f('ix_teachers_ci'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_table('planilla_outputs')
    op.drop_table('biometric_uploads')
    # ### end Alembic commands ###
